### ISSUE TITLE
setVolume is not working in both android and ios

### ISSUE THREAD

**Issue by techrishdev** [gandhirajan/Cordova_Media#1]
I tried to build a cordova project with this. Audio is working fine, but I cant set the volume. 'playMp3Mild' and 'playMP3' functions have same volume. Please help me to sort out this issue.

Thanks in advance.

**Comment by gandhirajan** [comment]
I have tried this in both Android 6 device and iPhone iOS version 9.2 It works fine. Are you testing on iOS or Android? Did you checked if there any issue with the plugin as such?

**Comment by techrishdev** [comment]
I build android using cordova in windows 7 and run using android 4, 5 and 6. But unfortunately volume is not changing.

Similarly iOS app is developed using Mac and tested on Xcode simulator. Same result.

I am attaching the android APK file and config file can you please check whether it is working or not.
Attachment url is http://techrish.in/volume/

**Comment by gandhirajan** [comment]
I have tried out in my setup as well and surprisingly it dint work either. Could you try out once in iOS? Looks like i have tried out only in iOS device to address this post - http://stackoverflow.com/questions/38059052/cordova-media-plugin-setvolume-not-working .May be i overlooked it. If possible will try to debug for any error in device console.

**Comment by techrishdev** [comment]
I tried using iphone 4, 5 and 6 using xcode simulator. Unfortunately the result is same. Can you send us the ipa file you created for testing in our device.

**Comment by gandhirajan** [comment]
Hi, sending IPA may not help as the provisioning profile certs wont allow you to install the IPA in your device. Have added iOS platform in the project. Generarte IPA out of it using Xcode and let me know. Also i noticed that the cordova version i m using in mac machine is 6.1.1 But the one is tested in android was using version 6.2.0 Not sure whether that makes any difference.

**Comment by gandhirajan** [comment]
Awaiting your confirmation. Will close the issue in some time if there is no response. Thanks

**Comment by techrishdev** [comment]
As you told, the IPA file is not supporting in our system.

We use audio tag volume control instead of media plugin.

**Comment by gandhirajan** [comment]
Thanks for your response. You could place the sample snippet with description of how you resolved the issue so that it can helpful for others too and i can close the issue. Cheers
